'use strict';

/* API keys — loaded from env.local.json generated by wscript from .env */
var localEnv = {};
try { localEnv = require('./env.local.json'); } catch (e) { localEnv = {}; }

exports.TRAIN_API_KEY = localEnv.TRAIN_API_KEY || '';
exports.BUS_API_KEY   = localEnv.BUS_API_KEY   || '';

/* AppMessage key constants (must match package.json messageKeys) */
exports.KEY_MSG_TYPE      = 0;
exports.KEY_STATION_NAME  = 1;
exports.KEY_ARRIVALS      = 2;
exports.KEY_LINE_COLOR    = 3;
exports.KEY_STATION_IDX   = 4;
exports.KEY_TOTAL_STNS    = 5;
exports.KEY_ERROR_MSG     = 6;
exports.KEY_STATION_META  = 7;
exports.KEY_THEME         = 8;

/* MsgType values C→JS */
exports.MSG_REQ_TRAIN = 0;
exports.MSG_REQ_BUS   = 1;
/* MsgType values JS→C */
exports.MSG_STATION   = 2;
exports.MSG_ERROR     = 3;
exports.MSG_THEME     = 4;

/* Theme values sent JS->C */
exports.THEME_DARK  = 0;
exports.THEME_LIGHT = 1;
exports.THEME_AUTO  = 2;

/* Timeouts and limits */
exports.FETCH_WATCHDOG_MS   = 12000;
exports.MAX_TRAIN_STATIONS  = 16;
exports.MAX_BUS_STOPS       = 16;
exports.MAX_TRAIN_ARRIVALS  = 3;
exports.MAX_BUS_PREDICTIONS = 3;

/* Settings persistence */
exports.SETTINGS_STORAGE_KEY = 'route_rush_settings_v1';
exports.DEFAULT_SETTINGS = {
  /* Clean imperial defaults (2.0 mi train, 0.5 mi bus), stored in km */
  trainRadiusKm: 2 / 0.621371,
  busRadiusKm:   0.5 / 0.621371,
  distanceUnit:  'metric',
  themeMode:     'auto'
};

/* CTA station data cache */
exports.CTA_STATIONS_CACHE_KEY = 'cta_stations_v1';
exports.CTA_STATIONS_TTL_MS    = 7 * 24 * 60 * 60 * 1000;
